# Site settings
title: Nagasundari Sivamoni Moorthy
name: Nagasundari Sivamoni Moorthy

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Microsoft/Phoenix
 - title: StackOverflow
   url: http://stackoverflow.com/users/258813/rhinds
 - title: LinkedIn
   url: https://www.linkedin.com/in/nagasundari-sivamoni-moorthy-56121a4b/

#Any buzzword skills you want to include
skills:
 - C#
 - ASP.Net
 - Web API
 - SQL
 - Javascript

#Work experience is required
roles:
- title: Software Development Engineer
   start: Nov 2016
   end: Nov 2018
   employer: Microsoft (Consultant)
   description: I worked on this project developing tools to run compliance scans on cloud and on-prem resources and reports the results for fixing the vulnerabilities. I developed secure libraries using Azure resources like Keyvault, Storage and Queues to accomplish compliance scans. 
- title: Software Development Engineer
   start: Nov 2014
   end: June 2016
   employer: Microsoft (Consultant)
   description: I worked on this project to develop various tools that operates the MSIT infrastructure and also works to deliver Data center capacity, optimize the usage of resources to drive down the operation costs. 
- title: Software Development Engineer in Test
   start: 2004
   end: 2012
   employer: Microsoft (Consultant)
   description: A range of projects within Microsoft working on developing tools for test automation.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   subject: Computer Science
   school: Madurai Kamaraj University

#List of interesting Github repo/projects to include - optional

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Work Authorization</strong>: Eligible to work for any employer - No Visa Required
   I am experienced in Microsoft technology stack, but open to learning others as well. I have recently worked on developing .net libraries that are encrypted the data in rest and in transit. <br/><br/>
   
